export {
  SEMANTIC_EMBEDDING_DIMENSIONS as BOOKMARKS_EMBEDDING_DIMENSIONS,
  SEMANTIC_INDEX_VERSION as BOOKMARKS_EMBEDDING_INDEX_VERSION,
  SEMANTIC_MODEL_ID as BOOKMARKS_EMBEDDING_MODEL_ID,
  SEMANTIC_RESULT_LIMIT as BOOKMARKS_SEMANTIC_RESULT_LIMIT,
} from '../../src/greenfield/semantic/config'
