export const BOOKMARKS_EMBEDDING_MODEL_ID = 'Xenova/clip-vit-base-patch32'
export const BOOKMARKS_EMBEDDING_DIMENSIONS = 512
export const BOOKMARKS_EMBEDDING_INDEX_VERSION = 1
export const BOOKMARKS_SEMANTIC_RESULT_LIMIT = 240
